# Математичекая Статистика
## Лабораторная Работа №4 «Линейные Модели», Вариант 2 4

Румянцев Алексей Александрович, 368731, Поток Мат Стат 31.2

## Задание 1
### Условие

Требуется построить линейную модель (предполагая нормальность распределения ошибок, некоррелированность компонент, гомоскедастичность), вычислить оценки коэффициентов модели и остаточной дисперсии, построить для них доверительные интервалы, вычислить коэффициент детерминации, проверить указанные в условии гипотезы с помощью построенной линейной модели.

**Указание**: из встроенных функций разрешается пользоваться квантильными функциями и средствами для квадратичной оптимизации (иными словами, готовую обертку для построения линейной модели не использовать, максимум можете сравнить вашу реализацию с готовой)

В файле [`mobile_phones.csv`](https://drive.google.com/file/d/1O4rFr9xg9aFmkjx4-hl_XOc5O9q65_EW/view) представлены данные о мобильных телефонах.
1. Постройте линейную модель, где в качестве независимых переменных выступают высота, ширина экрана (атрибуты `sc_h` и `sc_w`) и емкость аккумулятора (вместе со свободным коэффициентом), зависимой -- масса телефона.
2. Проверьте следующие подозрения:
    1. Чем больше высота экрана, тем больше масса
    2. Чем больше ширина экрана, тем больше масса
    3. Проверьте гипотезу $H_0$ о равенстве одновременно нулю коэффициентов при ширине экрана и емкости аккумулятора против альтернативы $H_1=\overline{H_0}$

### Выполнение

Основной источник информации, использовавшийся для выполнения лабораторной работы -- [презентация](https://drive.google.com/file/d/1ObI68ECLeasAhUNw7pVuLtcvW60I8tb_/view)


**Пункт 1.** Модель [линейной регрессии](https://en.wikipedia.org/wiki/Linear_regression) имеет вид

$$Y=Xc+\varepsilon$$
$$Y=\begin{bmatrix}y_1\\ y_2\\ \vdots \\ y_n\end{bmatrix},\ \ X=\begin{bmatrix}x_1^T\\ x_2^T\\ \vdots \\ x_n^T\end{bmatrix}=\begin{bmatrix}1 & x_{11} & \dots & x_{1p}\\ 1 & x_{21} & \dots & x_{2p}\\ \vdots & \vdots & \ddots & \vdots \\ 1 & x_{n1} & \dots & x_{np}\end{bmatrix},\ \ c=\begin{bmatrix}c_0\\c_1\\c_2\\ \vdots \\ c_p\end{bmatrix},\ \ \varepsilon=\begin{bmatrix}\varepsilon_1\\ \varepsilon_2\\ \vdots \\ \varepsilon_n\end{bmatrix}$$
Здесь $Y$ -- вектор наблюдаемых значений переменной $y_i\ (i=1,...,n)$, называемой регрессией, $X$ -- матрица дизайна из векторов регрессоров (независимые переменные и свободный коэффициент как вектор из единиц), $c$ -- вектор из коэффициентов регрессии размерности $p+1$, $p$ -- количество предикторов (независимых параметров), $\varepsilon$ -- вектор ошибок $\varepsilon_i$.


В нашем случае количество независимых параметров 3 плюс свободный коэффициент, тогда $p=4$. Обозначим
$$x_1\text{ -- высота экрана},$$
$$x_2\text{ -- ширина экрана},$$
$$x_3\text{ -- емкость аккумулятора},$$
тогда модель линейной регрессии примет вид
$$y=c_0+c_1x_1+c_2x_2+c_3x_3+\varepsilon$$
Зададим предположения на $\varepsilon$
$$\mathbb{E}\left[\varepsilon\right]=0,\ \ \text{Var}\left[\varepsilon_i\right]=\sigma^2\text{ -- гомоскедастичность}$$
$$\text{Cov}\left[\varepsilon_i,\varepsilon_j\right]=0\text{ -- некоррелированность компонент}$$
$$\varepsilon \sim \mathcal{N}\left(0,\sigma^2 I_n\right)\text{ -- нормальность распределения ошибок}$$
Предсказания линейной модели ищутся как
$$\hat{Y}=X\hat{c}$$
Здесь $\hat{c}$ -- оценки коэффициентов модели, которые выражаются как
$$\hat{c}=\text{arg min}_{\mathbb{R}^p}S^2\left[c\right]$$
Здесь $S^2\left[c\right]$ -- квадратическая ошибка, имеющая вид
$$S^2\left[c\right]=\left[Y-Xc\right]^T\left[Y-Xc\right]=\varepsilon^T\varepsilon$$
Обозначим
$$A=X^TX,\ \ \text{rank}\left[A\right]=p$$
Тогда, оценка коэффициентов модели имеет вид
$$\hat{c}=A^{-1}X^TY$$


Найдем сначала $\hat{c}$. Считаем и выведем таблицу

In [209]:
from pathlib import Path
import os

import pandas as pd


path = Path().resolve()
filename = 'mobile_phones.csv'
data = pd.read_csv(os.path.join(path, filename))
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

Составим $X$ по условию задания. Выведем количество элементов в таблице, ранг матрицы $X$ (он должен быть равен $p$) и саму матрицу дизайна

In [210]:
import numpy as np


n = data.shape[0]
ones = np.ones(n)
x_1 = data['sc_h'].values
x_2 = data['sc_w'].values
x_3 = data['battery_power'].values
X = np.column_stack([ones, x_1, x_2, x_3])
print(f'n={n}, rank(X)={np.linalg.matrix_rank(X)}')
X

n=2000, rank(X)=4


array([[1.000e+00, 9.000e+00, 7.000e+00, 8.420e+02],
       [1.000e+00, 1.700e+01, 3.000e+00, 1.021e+03],
       [1.000e+00, 1.100e+01, 2.000e+00, 5.630e+02],
       ...,
       [1.000e+00, 9.000e+00, 1.000e+00, 1.911e+03],
       [1.000e+00, 1.800e+01, 1.000e+01, 1.512e+03],
       [1.000e+00, 1.900e+01, 4.000e+00, 5.100e+02]])

Составим матрицу $A$ по формуле, приведенной ранее. Выведем ранг этой матрицы (он должен быть равен $p$) и саму матрицу

In [211]:
A = X.T @ X
print(f'rank(A)={np.linalg.matrix_rank(A)}')
A

rank(A)=4


array([[2.00000000e+03, 2.46130000e+04, 1.15340000e+04, 2.47703700e+06],
       [2.46130000e+04, 3.38385000e+05, 1.60514000e+05, 3.03727820e+07],
       [1.15340000e+04, 1.60514000e+05, 1.04454000e+05, 1.42031020e+07],
       [2.47703700e+06, 3.03727820e+07, 1.42031020e+07, 3.45383978e+09]])

Вычислим и выведем обратную матрицу к матрице $A$

In [212]:
A_m1 = np.linalg.inv(A)
A_m1

array([[ 9.00896294e-03, -3.68170381e-04,  2.10585144e-05,
        -3.31001806e-06],
       [-3.68170381e-04,  3.79053570e-05, -1.85401139e-05,
         6.95100030e-09],
       [ 2.10585144e-05, -1.85401139e-05,  3.54395632e-05,
         2.20056170e-09],
       [-3.31001806e-06,  6.95100030e-09,  2.20056170e-09,
         2.59324744e-09]])

По условию задания $Y$ -- масса телефона. Вычислим оценки коэффициентов модели по формуле, приведенной ранее. Выведем результат, должно получиться $p$ коэффициентов

In [213]:
Y = data['mobile_wt'].values
hat_c = A_m1 @ X.T @ Y
print(f'len(hat_c)={len(hat_c)}')
hat_c

len(hat_c)=4


array([ 1.43640572e+02, -2.63548169e-01, -3.95486159e-02,  6.44803879e-05])

Получили
$$\hat{c}_0\text{ -- оценка свободного коэффициента}$$
$$\hat{c}_1\text{ -- оценка коэффициента при высоте экрана}$$ 
$$\hat{c}_2\text{ -- оценка коэффициента при ширине экрана}$$
$$\hat{c}_3\text{ -- оценка коэффициента при емкости аккумулятора}$$
Воспользуемся этими коэффициентами для вычисления предсказаний $\hat{Y}$ по заданной $X$. Выведем результат

In [214]:
hat_Y = X @ hat_c
hat_Y

array([141.04609091, 139.10744201, 140.69874762, ..., 141.35231214,
       138.5987134 , 138.50784758])

Посчитаем и выведем квадратическую ошибку $S^2\left[\hat{c}\right]$. Формула приведена ранее

In [215]:
Y_m_Xc = Y - X @ hat_c
S2 = Y_m_Xc.T @ Y_m_Xc
S2

2502101.030648561

Вычислим оценку остаточной дисперсии. Формула имеет вид
$$\hat{\sigma}^2=\dfrac{S^2(\hat{c})}{n-p}$$
Напоминание: внутри $p$ уже учитываем наличие свободного коэффициента (вместе с тремя независимыми параметрами), поэтому $p=3+1$. Выведем результат $\hat{\sigma}^2$

In [216]:
p = 3 + 1
hat_sigma2 = S2 / (n - p)
hat_sigma2

1253.5576305854515

Найдем доверительный интервал для $c_j$. Отклонение оценки параметра $\hat{c}_j$​ от истинного значения $c_j$​, нормированное на его стандартную ошибку, подчиняется распределению Стьюдента с $n−p$ степенями свободы
$$\left(\hat{c}_j-c_j\right)\sqrt{\dfrac{n-p}{A^{-1}_{jj}S^2\left(\hat{c}\right)}}\sim T(n-p)$$
$$\left(\hat{c}_j-c_j\right)\sqrt{\dfrac{n-p}{A^{-1}_{jj}S^2\left(\hat{c}\right)}}\leq t_{1-\frac{\alpha}{2},n-p}$$
Распределение Стьюдента симметрично, как и нормальное, то есть $t_{\alpha/2}=-t_{1-\alpha/2}$
$$-t_{1-\frac{\alpha}{2},n-p}\leq \left(\hat{c}_j-c_j\right)\sqrt{\dfrac{n-p}{A^{-1}_{jj}S^2\left(\hat{c}\right)}}\leq t_{1-\frac{\alpha}{2},n-p}$$
Элементарными действиями выражаем неравенство относительно $c_j$
$$\hat{c}_j-t_{1-\frac{\alpha}{2},n-p}\sqrt{\dfrac{A^{-1}_{jj}S^2\left(\hat{c}\right)}{n-p}}\leq c_j\leq \hat{c}_j+t_{1-\frac{\alpha}{2},n-p}\sqrt{\dfrac{A^{-1}_{jj}S^2\left(\hat{c}\right)}{n-p}}$$
Зададим 5%-ый уровень значимости. Посчитаем доверительные интервалы для оценок коэффициентов и выведем результаты

In [217]:
import scipy.stats as st


alpha = 0.05
t_1m_a2 = st.t.ppf(1 - alpha / 2, df = n - p)
A_m1_diag = np.diagonal(A_m1)
se_hat_c = np.sqrt(A_m1_diag * S2 / (n - p))
interval_lower = hat_c - t_1m_a2 * se_hat_c
interval_upper = hat_c + t_1m_a2 * se_hat_c
print(f'confidence intervals for c_j:')
for j in range(p):
    print(f'{interval_lower[j]:.4f}<=c_{j}<={interval_upper[j]:.4f}')

confidence intervals for c_j:
137.0500<=c_0<=150.2311
-0.6910<=c_1<=0.1639
-0.4529<=c_2<=0.3738
-0.0035<=c_3<=0.0036


[Коэффициент детерминации](https://net-informations.com/ds/psa/adjusted.htm) выражается как
$$R^2=1-\dfrac{\sum_{j=1}^{n}\left(Y-\hat{Y}\right)^2}{\sum_{j=1}^{n}\left(Y-\overline{Y}\right)^2}$$
Чем ближе значение к 1, тем лучше модель объясняет данные, и тем сильнее зависимость между переменными. Посчитаем и выведем $R^2$

In [218]:
R2 = 1 - np.sum((Y - hat_Y) ** 2) / np.sum((Y - Y.mean()) ** 2)
R2

0.0011644496581528774

Похоже, что модель почти не объясняет вариацию зависимой переменной.

**Пункт 2.** Проверка гипотез. Зададим функцию проверки гипотез

In [219]:
ACCEPT = "Accept null hypothesis"
REJECT = "Reject null hypothesis with respect to given alternative"

def print_reject_or_accept(condition):
  if condition:
    print(REJECT)
  else:
    print(ACCEPT)

**Пункт 2.1.** Проверим подозрение "Чем больше высота экрана, тем больше масса". Гипотезы будут иметь вид
$$H_0: c_1=0\text{, масса не зависит от высоты экрана}$$
$$H_1: c_1>0\text{, чем больше высота экрана, тем больше масса}$$
В случае модели линейной регрессии используем [$t$-тест](https://books.econ.msu.ru/Introduction-to-Econometrics/chap03/3.5/) для $c_j$-го коэффициента
$$t=\dfrac{\hat{c}_j}{\text{SE}\left[\hat{c}_j\right]}$$
Посчитаем и выведем $t$-статистику

In [220]:
t_score = hat_c[1] / se_hat_c[1]
t_score

-1.2090313328632147

Зададим 5%-ый уровень значимости. Посчитаем квантильной функцией критическое значение статистики. Если $t>t_{crit}=t_{1-\alpha,n-p}$, то нулевая гипотеза отвергается (тест правосторонний). Выведем результат

In [221]:
alpha = 0.05
t_crit = st.t.ppf(1 - alpha, df = n - p)
t_crit

1.6456173949469155

Проверим гипотезу. Модуль на статистику не нужен, тест односторонний, учитываем направление. Выведем результат

In [222]:
print_reject_or_accept(t_score > t_crit)

Accept null hypothesis


Таким образом, **нулевая гипотеза $H_0$ не отвергается**. Для наших данных скорее всего масса телефона не зависит от высоты экрана

**Пункт 2.2.** Проверим подозрение "Чем больше ширина экрана, тем больше масса". Решение аналогично. Зададим гипотезы
$$H_0: c_2=0\text{, масса не зависит от ширины экрана}$$
$$H_1: c_2>0\text{, чем больше ширина экрана, тем больше масса}$$
Проделаем те же шаги, что и для предыдущего пункта. Выведем значение статистики, критическое значение (тест односторонний) и результат проверки гипотез

In [223]:
t_score = hat_c[2] / se_hat_c[2]
alpha = 0.05
t_crit = st.t.ppf(1 - alpha, df = n - p)
print(f't_score={t_score}, t_crit={t_crit}')
print_reject_or_accept(t_score > t_crit)

t_score=-0.18763547736466346, t_crit=1.6456173949469155
Accept null hypothesis


**Принимаем нулевую гипотезу $H_0$**. Возможно на наших данных масса телефона не зависит от ширины экрана.

**Пункт 2.3.** Проверим гипотезу $H_0$ о равенстве одновременно нулю коэффициентов при ширине экрана и емкости аккумулятора против альтернативы $H_1=\overline{H_0}$. $H_1$ -- по крайней мере один из коэффициентов не равен нулю. Гипотезы будут иметь вид
$$H_0: c_2=c_3=0$$
$$H_1: \begin{align*}\left[\begin{array}{ll}c_2\neq 0\\ c_3\neq 0\end{array}\right . \end{align*}$$
Проверять будем с помощью [$F$-теста](https://ru.wikipedia.org/wiki/F-%D1%82%D0%B5%D1%81%D1%82). Статистика подчиняется распределению Фишера с $n-p_L$ степенями свободы и имеет вид
$$F=\dfrac{(S^2_S - S^2_L)/q}{S^2_L/(n-p_L)}\sim F\left(q,n-p_L\right)$$
Здесь индексы $S$ и $L$ относятся соответственно к короткой (с ограничениями) и длинной (без ограничений) моделям, $q=p_L-p_S$ -- количество ограничений.

Создадим ограниченную модель, исключив из нашей модели ширину экрана и емкость аккумулятора (следовательно, кол-во ограничений $p_S=2$). Все шаги аналогичны шагам для построения полной модели. Посчитаем статистику согласно формуле и выведем результат

In [224]:
X_S = np.column_stack([ones, x_1])
A_S = X_S.T @ X_S
A_S_m1 = np.linalg.inv(A_S)
hat_c_S = A_S_m1 @ X_S.T @ Y
Y_m_Xc_S = Y - X_S @ hat_c_S
S2_S = Y_m_Xc_S.T @ Y_m_Xc_S
p_S = 2
q = p - p_S
f_score = ((S2_S - S2) / q) / (S2 / (n - p))
f_score

0.018292704595200437

Посчитаем критическое значение статистики. Тест правосторонний. Если $F>F_{crit}=f_{1-\alpha,\ dfn,\ dfd}$, где $dfn$ -- число ограничений на $H_0$, $dfd$ -- степени свободы неограниченной модели, то нулевая гипотеза отвергается. Оставим 5%-ый уровень значимости. Выведем результат

In [225]:
alpha = 0.05
f_crit = st.f.ppf(1 - alpha, dfn = q, dfd = n - p)
f_crit

3.0002329740570084

Выведем результат проверки гипотез

In [226]:
print_reject_or_accept(f_score > f_crit)

Accept null hypothesis


**Нулевая гипотеза $H_0$ не отвергается**. Выходит, что для наших данных скорее всего предикторы $x_2$ и $x_3$ не оказывают значимого влияния на зависимую переменную (массу телефона).

## Задание 2
### Условие

Требуется проверить гипотезу о равенстве средних на каждом уровне фактора с помощью модели однофакторного дисперсионного анализа.

**Указание**: реализовать самим.

В файле [`mobile_phones.csv`](https://drive.google.com/file/d/1O4rFr9xg9aFmkjx4-hl_XOc5O9q65_EW/view) приведены данные о мобильных телефонах. Фактор -- ценовая категория, выходная переменная -- емкость аккумулятора.

### Выполнение

Нулевая гипотеза -- средние значения емкости аккумулятора для всех уровней ценовой категории одинаковы, альтернативная -- средние значения емкости аккумулятора для хотя бы двух уровней ценовой категории различны
$$H_0: \mu_1=\mu_2=...=\mu_J$$
$$H_1: \exists\ \mu_i,\mu_j: \mu_i\neq\mu_j,\ i\neq j,\ i,j\leq J$$
Для решения задачи понадобится частный случай линейной модели "One-way ANOVA". Статистика подчиняется распределению Фишера со степенями свободы $J-1$ для межгрупповой дисперсии и $I-J$ для внутригрупповой и имеет вид
$$F=\dfrac{MS_B}{MS_W}\sim F\left(J-1,I-J\right)$$
Здесь $I=I_1+I_2+...+I_J$ -- общее число наблюдений в группах ($i$ -- номер наблюдения, $1\leq i\leq I_J$), $J$ -- количество уровней фактора ($j$ -- уровень фактора, $1\leq j\leq J$), $MS_B$ -- оценка межгрупповой дисперсии
$$MS_B=\dfrac{S_B}{J-1},\ \ S_B=\sum\limits_{j=1}^{J}n_j\left(\overline{y_{*,j}}-\overline{y}\right)^2,$$
где $n_j$ -- размер $j$-ой группы, $\overline{y_{*,j}}$ -- усреднение внутри группы, т.е. при фиксированном $j$. $MS_W$ -- оценка внутригрупповой дисперсии
$$MS_W=\dfrac{S_w}{I - J},\ \ S_W=\sum_{j}^{J}\sum_{i}^{I_J}\left(y_{i,j}-\overline{y_{*,j}}\right)^2$$
Критическая область -- правосторонняя.

Считаем данные и выведем таблицу

In [227]:
from pathlib import Path
import os

import pandas as pd


path = Path().resolve()
filename = 'mobile_phones.csv'
data = pd.read_csv(os.path.join(path, filename))
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

Нам понадобятся столбцы `price_range` и `battery_power`. Разделим `battery_power` на группы в соответствии со значениями `price_range`. В группах будут находиться $$y_{i,j}=\mu_j+\varepsilon_{i,j},$$ где $\varepsilon_{i,j}$ -- центрированные независимые гауссовские величины с одинаковой дисперсией. Выведем количество групп и соответствующую каждой группе размерность

In [228]:
groups = data.groupby('price_range')['battery_power']
groups.size()

price_range
0    500
1    500
2    500
3    500
Name: battery_power, dtype: int64

Вышло 4 группы `price_range` по 500 элементов из `battery_power`. Найдем усреднения внутри группы $\overline{y_{*,j}}$ и общее среднее $\overline{y}$ по всем группам. Выведем результаты

In [ ]:
y_xj_mean = groups.mean()
y_mean = data['battery_power'].mean()
print(f'y_*j_mean:\n{y_xj_mean}\ny_mean={y_mean}')

y_*j_mean:
price_range
0    1116.902
1    1228.868
2    1228.320
3    1379.984
Name: battery_power, dtype: float64
y_mean=1238.5185


Посчитаем $S_W$ по приведенной ранее формуле. Выведем результат

In [230]:
J = len(data['price_range'].unique())
S_W = 0
for j in range(J):
    group = groups.get_group(j)
    y_ij_mean = y_xj_mean.values[j]
    for y_ij in group:
        S_W += (y_ij - y_ij_mean) ** 2
S_W

368483530.1580001

В соответствии с формулой, приведенной ранее, вычислим значение $MS_W$. Выведем результат

In [231]:
I = len(data)
MS_W = S_W / (I - J)
MS_W

184610.98705310628

Вычислим по приведенной ранее формуле $S_B$. Выведем результат

In [232]:
n_j = groups.size().values
S_B = np.sum(n_j * (y_xj_mean.values - y_mean) ** 2)
S_B

17500101.157499984

Используем $S_B$ для вычисления $MS_B$ в соответствии с приведенной ранее формулой. Выведем результат

In [233]:
MS_B = S_B / (J - 1)
MS_B

5833367.052499995

Посчитаем и выведем статистику, используя формулу, приведенную в теории для задания

In [234]:
f_score = MS_B / MS_W
f_score

31.598157539897308

Найдем критическое значение статистики. Напоминание: тест правосторонний. Если $F>F_{crit}=f_{1-\alpha,\ dfn,\ dfd}$, где $dfn$ -- степени свободы для межгрупповой дисперсии $MS_B$, $dfd$ -- степени свободы для внутригрупповой дисперсии $MS_W$, то отвергаем нулевую гипотезу. Оставим 5%-ый уровень значимости. Выведем результат

In [235]:
alpha = 0.05
f_crit = st.f.ppf(1 - alpha, dfn = J - 1, dfd = I - J)
f_crit

2.6093607480930223

Воспользуемся функцией для проверки гипотез. Выведем результат

In [236]:
print_reject_or_accept(f_score > f_crit)

Reject null hypothesis with respect to given alternative


Таким образом, **отвергаем нулевую гипотезу $H_0$**. Для наших данных ценовая категория влияет на емкость аккумулятора.

Проверим наши вычисления библиотечной функцией `f_oneway`. Выведем статистику

In [237]:
group_1 = groups.get_group(0)
group_2 = groups.get_group(1)
group_3 = groups.get_group(2)
group_4 = groups.get_group(3)
f_stat, p_value = st.f_oneway(group_1, group_2, group_3, group_4)
f_stat

31.598157539897333

Разница между нашими вычислениями и библиотечными минимальна, следовательно статистика посчитана верно. Наши выводы корректны