# Математичекая Статистика
## Лабораторная Работа №4 «Линейные Модели», Вариант 2 4

Румянцев Алексей Александрович, 368731, Поток Мат Стат 31.2

## Задание 1
### Условие

Требуется построить линейную модель (предполагая нормальность распределения ошибок, некоррелированность компонент, гомоскедастичность), вычислить оценки коэффициентов модели и остаточной дисперсии, построить для них доверительные интервалы, вычислить коэффициент детерминации, проверить указанные в условии гипотезы с помощью построенной линейной модели.

**Указание**: из встроенных функций разрешается пользоваться квантильными функциями и средствами для квадратичной оптимизации (иными словами, готовую обертку для построения линейной модели не использовать, максимум можете сравнить вашу реализацию с готовой)

В файле [`mobile_phones.csv`](https://drive.google.com/file/d/1O4rFr9xg9aFmkjx4-hl_XOc5O9q65_EW/view) представлены данные о мобильных телефонах.
1. Постройте линейную модель, где в качестве независимых переменных выступают высота, ширина экрана (атрибуты `sc_h` и `sc_w`) и емкость аккумулятора (вместе со свободным коэффициентом), зависимой -- масса телефона.
2. Проверьте следующие подозрения:
    1. Чем больше высота экрана, тем больше масса
    2. Чем больше ширина экрана, тем больше масса
    3. Проверьте гипотезу $H_0$ о равенстве одновременно нулю коэффициентов при ширине экрана и емкости аккумулятора против альтернативы $H_1=\overline{H_0}$

### Выполнение

**Пункт 1.** [Источник 1](https://en.wikipedia.org/wiki/Linear_regression), [Источник 2](https://drive.google.com/file/d/1ObI68ECLeasAhUNw7pVuLtcvW60I8tb_/view), [Источник 3](https://net-informations.com/ds/psa/adjusted.htm), [Источник 4](https://books.econ.msu.ru/Introduction-to-Econometrics/chap03/3.5/), [Источник 5](https://ru.wikipedia.org/wiki/F-%D1%82%D0%B5%D1%81%D1%82)

$$Y=Xc+\varepsilon$$
$$Y=\begin{bmatrix}y_1\\ y_2\\ \vdots \\ y_n\end{bmatrix},\ \ X=\begin{bmatrix}x_1^T\\ x_2^T\\ \vdots \\ x_n^T\end{bmatrix}=\begin{bmatrix}1 & x_{11} & \dots & x_{1p}\\ 1 & x_{21} & \dots & x_{2p}\\ \vdots & \vdots & \ddots & \vdots \\ 1 & x_{n1} & \dots & x_{np}\end{bmatrix},\ \ c=\begin{bmatrix}c_0\\c_1\\c_2\\ \vdots \\ c_p\end{bmatrix},\ \ \varepsilon=\begin{bmatrix}\varepsilon_1\\ \varepsilon_2\\ \vdots \\ \varepsilon_n\end{bmatrix}$$
$$y=c_0+c_1x_1+c_2x_2+c_3x_3+\varepsilon$$
Предполагаем, что
$$\mathbb{E}\left[\varepsilon\right]=0,\ \ \text{Var}\left[\varepsilon_i\right]=\sigma^2,\ \ \text{Cov}\left[\varepsilon_i,\varepsilon_j\right]=0,\ \ \varepsilon \sim \mathcal{N}\left(0,\sigma^2 I_n\right)$$
Ищем
$$\hat{c}=\text{arg min}_{\mathbb{R}^p}S^2\left[c\right]$$
Квадратическая ошибка
$$S^2\left[c\right]=\left[Y-Xc\right]^T\left[Y-Xc\right]=\varepsilon^T\varepsilon$$
Количество предикторов $p$ это независимые параметры плюс свободный коэффициент
$$A=X^TX,\ \ \text{rank}\left[A\right]=p$$
Таким образом, оценка коэффициентов модели имеет вид
$$\hat{c}=A^{-1}X^TY$$
Линейная модель будет иметь вид
$$\hat{Y}=X\hat{c}$$
Оценка остаточной дисперсии
$$\hat{\sigma}^2=\dfrac{S^2(\hat{c})}{n-p}$$
Доверительный интервал для $c_j$
$$\left(\hat{c}_j-c_j\right)\sqrt{\dfrac{n-p}{A^{-1}_{jj}S^2\left(\hat{c}\right)}}\sim T(n-p)$$
$$\left(\hat{c}_j-c_j\right)\sqrt{\dfrac{n-p}{A^{-1}_{jj}S^2\left(\hat{c}\right)}}\leq t_{1-\frac{\alpha}{2},n-p}$$
$$-t_{1-\frac{\alpha}{2},n-p}\leq \left(\hat{c}_j-c_j\right)\sqrt{\dfrac{n-p}{A^{-1}_{jj}S^2\left(\hat{c}\right)}}\leq t_{1-\frac{\alpha}{2},n-p}$$
$$\hat{c}_j-t_{1-\frac{\alpha}{2},n-p}\sqrt{\dfrac{A^{-1}_{jj}S^2\left(\hat{c}\right)}{n-p}}\leq c_j\leq \hat{c}_j+t_{1-\frac{\alpha}{2},n-p}\sqrt{\dfrac{A^{-1}_{jj}S^2\left(\hat{c}\right)}{n-p}}$$
Коэффициент детерминации
$$R^2=1-\dfrac{\sum_{j=1}^{n}\left(Y-\hat{Y}\right)^2}{\sum_{j=1}^{n}\left(Y-\overline{Y}\right)^2}$$

In [117]:
from pathlib import Path
import os

import pandas as pd


path = Path().resolve()
filename = 'mobile_phones.csv'
data = pd.read_csv(os.path.join(path, filename))
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [118]:
import numpy as np


n = data.shape[0]
ones = np.ones(n)
x_1 = data['sc_h'].values
x_2 = data['sc_w'].values
x_3 = data['battery_power'].values
X = np.column_stack([ones, x_1, x_2, x_3])
print(f'n={n}, rank(X)={np.linalg.matrix_rank(X)}')
X

n=2000, rank(X)=4


array([[1.000e+00, 9.000e+00, 7.000e+00, 8.420e+02],
       [1.000e+00, 1.700e+01, 3.000e+00, 1.021e+03],
       [1.000e+00, 1.100e+01, 2.000e+00, 5.630e+02],
       ...,
       [1.000e+00, 9.000e+00, 1.000e+00, 1.911e+03],
       [1.000e+00, 1.800e+01, 1.000e+01, 1.512e+03],
       [1.000e+00, 1.900e+01, 4.000e+00, 5.100e+02]])

In [119]:
A = X.T @ X
print(f'rank(A)={np.linalg.matrix_rank(A)}')
A

rank(A)=4


array([[2.00000000e+03, 2.46130000e+04, 1.15340000e+04, 2.47703700e+06],
       [2.46130000e+04, 3.38385000e+05, 1.60514000e+05, 3.03727820e+07],
       [1.15340000e+04, 1.60514000e+05, 1.04454000e+05, 1.42031020e+07],
       [2.47703700e+06, 3.03727820e+07, 1.42031020e+07, 3.45383978e+09]])

In [120]:
A_m1 = np.linalg.inv(A)
print(f'rank(A^(-1))={np.linalg.matrix_rank(A_m1)}')
A_m1

rank(A^(-1))=4


array([[ 9.00896294e-03, -3.68170381e-04,  2.10585144e-05,
        -3.31001806e-06],
       [-3.68170381e-04,  3.79053570e-05, -1.85401139e-05,
         6.95100030e-09],
       [ 2.10585144e-05, -1.85401139e-05,  3.54395632e-05,
         2.20056170e-09],
       [-3.31001806e-06,  6.95100030e-09,  2.20056170e-09,
         2.59324744e-09]])

In [121]:
Y = data['mobile_wt'].values
hat_c = A_m1 @ X.T @ Y
print(f'len(hat_c)={len(hat_c)}')
hat_c

len(hat_c)=4


array([ 1.43640572e+02, -2.63548169e-01, -3.95486159e-02,  6.44803879e-05])

$\hat{c}_0$ -- оценка свободного коэффициента, $\hat{c}_1$ -- оценка коэффициента при высоте экрана, $\hat{c}_2$ -- оценка коэффициента при ширине экрана, $\hat{c}_3$ -- оценка коэффициента при емкости аккумулятора

In [122]:
hat_Y = X @ hat_c
hat_Y

array([141.04609091, 139.10744201, 140.69874762, ..., 141.35231214,
       138.5987134 , 138.50784758])

In [123]:
err = Y - hat_Y
err

array([ 46.95390909,  -3.10744201,   4.30125238, ..., -33.35231214,
         6.4012866 ,  29.49215242])

In [124]:
Y_m_Xc = Y - X @ hat_c
S2 = Y_m_Xc.T @ Y_m_Xc
S2

2502101.030648561

$x_1, x_2, x_3$ и свободный коэффициент $p=4$

In [125]:
p = 3 + 1
sigma2 = S2 / (n - p)
sigma2

1253.5576305854515

In [126]:
import scipy.stats as st


alpha = 0.05
t_1m_a2 = st.t.ppf(1 - alpha / 2, df = n - p)
A_m1_diag = np.diagonal(A_m1)
se_hat_c = np.sqrt(A_m1_diag * S2 / (n - p))
interval_lower = hat_c - t_1m_a2 * se_hat_c
interval_upper = hat_c + t_1m_a2 * se_hat_c
print(f'confidence intervals for c_j:')
for j in range(p):
    print(f'{interval_lower[j]:.4f}<=c_{j}<={interval_upper[j]:.4f}')

confidence intervals for c_j:
137.0500<=c_0<=150.2311
-0.6910<=c_1<=0.1639
-0.4529<=c_2<=0.3738
-0.0035<=c_3<=0.0036


In [127]:
R2 = 1 - np.sum((Y - hat_Y) ** 2) / np.sum((Y - Y.mean()) ** 2)
R2

0.0011644496581528774

**Пункт 2.** Проверка гипотез

In [128]:
ACCEPT = "Accept null hypothesis"
REJECT = "Reject null hypothesis with respect to given alternative"

def print_reject_or_accept(condition):
  if condition:
    print(REJECT)
  else:
    print(ACCEPT)

**Пункт 2.1.** "Чем больше высота экрана, тем больше масса"
$$H_0: c_1=0\text{, масса не зависит от высоты экрана}$$
$$H_1: c_1>0\text{, чем больше высота экрана, тем больше масса}$$
$t$-тест для $c_j$-го коэффициента
$$t=\dfrac{\hat{c}_j}{\text{SE}\left[\hat{c}_j\right]}$$
Если $t>t_{crit}=t_{1-\alpha,n-p}$, то нулевая гипотеза отвергается (тест правосторонний)

In [129]:
t_score = hat_c[1] / se_hat_c[1]
t_score

-1.2090313328632147

In [130]:
alpha = 0.05
t_crit = st.t.ppf(1 - alpha, df = n - p)
t_crit

1.6456173949469155

Модуль на статистику не нужен, тест односторонний, учитываем направление

In [131]:
print_reject_or_accept(t_score > t_crit)

Accept null hypothesis


**Пункт 2.2.** "Чем больше ширина экрана, тем больше масса". Аналогично
$$H_0: c_2=0\text{, масса не зависит от ширины экрана}$$
$$H_1: c_2>0\text{, чем больше ширина экрана, тем больше масса}$$

In [132]:
t_score = hat_c[2] / se_hat_c[2]
alpha = 0.05
t_crit = st.t.ppf(1 - alpha, df = n - p)
print(f't_score={t_score}, t_crit={t_crit}')
print_reject_or_accept(t_score > t_crit)

t_score=-0.18763547736466346, t_crit=1.6456173949469155
Accept null hypothesis


**Пункт 2.3.** "Проверьте гипотезу $H_0$ о равенстве одновременно нулю коэффициентов при ширине экрана и емкости аккумулятора против альтернативы $H_1=\overline{H_0}$". $H_1$ -- по крайней мере один из коэффициентов не равен нулю
$$H_0: c_2=c_3=0$$
$$H_1: \begin{align*}\left[\begin{array}{ll}c_2\neq 0\\ c_3\neq 0\end{array}\right . \end{align*}$$
Понадобится $F$-тест
$$F=\dfrac{(S^2_S - S^2_L)/q}{S^2_L/(n-p_L)}\sim F\left(q,n-p_L\right)$$
Здесь индексы $S$ и $L$ относятся соответственно к короткой (с ограничениями) и длинной (без ограничений) моделям, $q=p_L-p_S$ -- количество ограничений. Создадим ограниченную модель, исключив из нашей модели ширину экрана и емкость аккумулятора

In [133]:
X_S = np.column_stack([ones, x_1])
A_S = X_S.T @ X_S
A_S_m1 = np.linalg.inv(A_S)
hat_c_S = A_S_m1 @ X_S.T @ Y
Y_m_Xc_S = Y - X_S @ hat_c_S
S2_S = Y_m_Xc_S.T @ Y_m_Xc_S
p_S = 2
q = p - p_S
f_score = ((S2_S - S2) / q) / (S2 / (n - p))
f_score

0.018292704595200437

Тест правосторонний. Если $F>F_{crit}=f_{1-\alpha,\ dfn,\ dfd}$, где $dfn$ -- число ограничений на $H_0$, $dfd$ -- степени свободы неограниченной модели, то нулевая гипотеза отвергается

In [134]:
alpha = 0.05
f_crit = st.f.ppf(1 - alpha, dfn = q, dfd = n - p)
f_crit

3.0002329740570084

In [135]:
print_reject_or_accept(f_score > f_crit)

Accept null hypothesis


## Задание 2
### Условие

Требуется проверить гипотезу о равенстве средних на каждом уровне фактора с помощью модели однофакторного дисперсионного анализа.

**Указание**: реализовать самим.

В файле [`mobile_phones.csv`](https://drive.google.com/file/d/1O4rFr9xg9aFmkjx4-hl_XOc5O9q65_EW/view) приведены данные о мобильных телефонах. Фактор -- ценовая категория, выходная переменная -- емкость аккумулятора.

### Выполнение

Нулевая гипотеза -- средние значения емкости аккумулятора для всех уровней ценовой категории одинаковы, альтернативная -- средние значения емкости аккумулятора для хотя бы двух уровней ценовой категории различны
$$H_0: \mu_1=\mu_2=...=\mu_J$$
$$H_1: \exists\ \mu_i,\mu_j: \mu_i\neq\mu_j,\ i\neq j,\ i,j\leq J$$
Нам понадобится частный случай линейной модели "One-way ANOVA". Статистика имеет вид
$$F=\dfrac{MS_B}{MS_W}\sim F\left(J-1,I-J\right)$$
Здесь $I=I_1+I_2+...+I_J$ -- общее число наблюдений в группах ($i$ -- номер наблюдения, $1\leq i\leq I_J$), $J$ -- количество уровней фактора ($j$ -- уровень фактора, $1\leq j\leq J$), $MS_B$ -- оценка межгрупповой дисперсии
$$MS_B=\dfrac{S_B}{J-1},\ \ S_B=\sum\limits_{j=1}^{J}n_j\left(\overline{y_{*,j}}-\overline{y}\right)^2,$$
где $n_j$ -- размер $j$-ой группы, $\overline{y_{*,j}}$ -- усреднение внутри группы, т.е. при фиксированном $j$. $MS_W$ -- оценка внутригрупповой дисперсии
$$MS_W=\dfrac{S_w}{I - J},\ \ S_W=\sum_{j}^{J}\sum_{i}^{I_J}\left(y_{i,j}-\overline{y_{*,j}}\right)^2$$
Критическая область -- правосторонняя

In [136]:
from pathlib import Path
import os

import pandas as pd


path = Path().resolve()
filename = 'mobile_phones.csv'
data = pd.read_csv(os.path.join(path, filename))
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

В группах содержатся $$y_{i,j}=\mu_j+\varepsilon_{i,j},$$ где $\varepsilon_{i,j}$ -- центрированные независимые гауссовские величины с одинаковой дисперсией

In [137]:
groups = data.groupby('price_range')['battery_power']
groups.size()

price_range
0    500
1    500
2    500
3    500
Name: battery_power, dtype: int64

In [138]:
y_xj_mean = groups.mean()
y_mean = data['battery_power'].mean()
print(f'y_*j_mean:\n{y_xj_mean}\ny_mean={y_mean}')

y_*j_mean:
price_range
0    1116.902
1    1228.868
2    1228.320
3    1379.984
Name: battery_power, dtype: float64
y_mean=1238.5185


In [144]:
J = len(data['price_range'].unique())
S_W = 0
for j in range(J):
    group = groups.get_group(j)
    y_ij_mean = y_xj_mean.values[j]
    for y_ij in group:
        S_W += (y_ij - y_ij_mean) ** 2
S_W

368483530.1580001

In [140]:
I = len(data)
MS_W = S_W / (I - J)
MS_W

184610.98705310628

In [141]:
n_j = groups.size().values
S_B = np.sum(n_j * (y_xj_mean.values - y_mean) ** 2)
S_B

17500101.157499984

In [142]:
MS_B = S_B / (J - 1)
MS_B

5833367.052499995

In [145]:
f_score = MS_B / MS_W
f_score

31.598157539897308

Если $F>F_{crit}=f_{1-\alpha,\ dfn,\ dfd}$, где $dfn$ -- степени свободы для межгрупповой дисперсии $MS_B$, $dfd$ -- степени свободы для внутригрупповой дисперсии $MS_W$, то отвергаем нулевую гипотезу

In [146]:
alpha = 0.05
f_crit = st.f.ppf(1 - alpha, dfn = J - 1, dfd = I - J)
f_crit

2.6093607480930223

In [147]:
print_reject_or_accept(f_score > f_crit)

Reject null hypothesis with respect to given alternative


Проверка

In [149]:
group_1 = groups.get_group(0)
group_2 = groups.get_group(1)
group_3 = groups.get_group(2)
group_4 = groups.get_group(3)
f_stat, p_value = st.f_oneway(group_1, group_2, group_3, group_4)
f_stat

31.598157539897333